[project]
name = "leaderboard"
version = "1.0.0"
description = "A Discord bot for tracking user message and attachment counts in a guild."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "yeetnspagoot", email = "yeetnspagoot@proton.me" }
]
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "hikari>=2.6.0",
    "hikari-lightbulb>=3.2.6",
    "python-dotenv>=1.2.3",
]

[project.scripts]
leaderboard = "leaderboard.__main__:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
